[project]
name = "backend"
authors = []
description = ""
telemetry = true

[[project.requirements]]
contract_id = "SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.commission-trait"

[[project.requirements]]
contract_id = "SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.gamma-commission-v1"



cache_dir = "C:\\Users\\HP\\.clarinet\\cache"
boot_contracts = ["pox", "costs-v2", "bns"]
depends_on = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []

[contracts.chifi-bots-packs-nft]
path = "contracts/chifi-bots-packs-nft.clar"
depends_on = ["sip009-nft-trait"]


[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
